name: Databricks Validation & Testing

on:
  push:
    branches:
      - feature/**
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:

  # =========================
  # 1. Validate Bundle Config
  # =========================
  validate-bundle:
    name: Validate Bundle Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks Bundle
        run: |
          databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

 # =========================
# 2. Run Bronze Unit Tests
# =========================
  run-bronze-tests:
    name: Run Bronze Unit Tests
    runs-on: ubuntu-latest
    needs: validate-bundle

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest databricks-connect

      - name: Run Bronze tests
        run: |
          pytest tests/bronze_testing -v --maxfail=1 --disable-warnings
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_SERVERLESS_COMPUTE_ID: "auto"

  # =========================
  # 3. Run Silver Unit Tests (Parallel)
  # =========================
  # run-silver-tests:
  #   name: Run Silver Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: validate-bundle

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip uninstall -y pyspark pyspark-connect databricks-connect || true
  #         pip install pytest databricks-connect

  #     - name: Run Silver tests
  #       run: |
  #         pytest tests/silver_testing -v --maxfail=1 --disable-warnings
  #       env:
  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  #         DATABRICKS_SERVERLESS_COMPUTE_ID: "auto"

  # # =========================
  # # 3. Run Gold  Unit Tests
  # # =========================
  # run-gold-tests:
  #   name: Run Gold Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: validate-bundle

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"

  #     - name: Install dependencies
  #       run: |
  #         pip install --upgrade pip
  #         pip uninstall -y pyspark pyspark-connect databricks-connect || true
  #         pip install pytest databricks-connect

  #     - name: Run Gold tests
  #       run: |
  #         pytest tests/gold_testing -v --maxfail=1 --disable-warnings
  #       env:
  #         DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  #         DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  #         DATABRICKS_SERVERLESS_COMPUTE_ID: "auto"

  # validate-and-deploy:
  #   name: Validate and Deploy Bundle
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
  #   needs: [validate-bundle, run-bronze-tests, run-silver-tests, run-gold-tests]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - name: Install Databricks CLI
  #       uses: databricks/setup-cli@main
  #     - name: Auto merge to main branch
  #       run:
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}